# Project
mod_version=1.1.0
maven_group=com.cerbon.prehistoric_paintings

# Minecraft
minecraft_version=1.21.1
minecraft_version_range_forge=[1.21,)
minecraft_version_range_fabric=>=1.21

# Forge
forge_version=52.1.0
forge_version_range=[51,)
loader_version_range=[51,)

# Fabric
fabric_loader_version=0.16.13
fabric_api_version=0.115.4
fabric_loader_version_range=>=0.15.6

# NeoForge
neo_version=21.1.145
neo_version_range=[21.0,)
neo_loader_version_range=[1,)

# Mappings
mapping_version=1.21.1:2024.11.17

# Mod Properties
mod_id=prehistoric_paintings
mod_name=Prehistoric Paintings
archives_base_name=prehistoric_paintings

mod_license=GNU LGPL 3.0
mod_authors=CerbonXD
mod_description=Modify vanilla paintings to pre-historic ones.

source_code_url=https://github.com/CERBON-s-Comissions/Prehistoric-Paintings
issues_url=https://github.com/CERBON-s-Comissions/Prehistoric-Paintings/issues
curseforge_url=

logo_file=logo.png

# General Dependencies
cerbons_api_version=1.1.1
cerbons_api_version_range_forge=[1.1.0,)
cerbons_api_version_range_fabric=>=1.1.0

mixin_extras_version=0.3.5

# Forge Dependencies

# Fabric Dependencies
cardinal_components_version=6.1.2

# NeoForge Dependencies

# Useful Mods
jei_version=19.21.0.247

jade_version_forge=
jade_version_fabric=6291536
jade_version_neo=6291517

modmenu_version_fabric=11.0.3

# CurseForge Gradle and Minotaur
curseforge_project_id=000000
modrinth_project_id=ABCDEFGH

release_type=release
changelog_type=markdown
changelog=CHANGELOG.md

game_versions=

required_dependencies_forge=
required_dependencies_fabric=fabric-api
required_dependencies_neo=

# JVM Arguments
org.gradle.jvmargs=-Xmx5G